export enum MessageType {
  MESSAGE_TO_ALL = 'MESSAGE_TO_ALL',
  CHATROOM_MESSAGE = 'CHATROOM_MESSAGE',
  CREATE_CHATROOM = 'CREATE_CHATROOM',
  ADD_TO_CHATROOM = 'ADD_TO_CHATROOM',
  ERROR = 'ERROR_MESSAGE',
}
